project: 
  type: manuscript
  render:
    - paper.qmd
    - notebooks/portable-full-comparison.ipynb
    - notebooks/h5py.ipynb
    - optimize.py
  output-dir: docs
manuscript:
  article: paper.qmd
format:
  agu-html:
    keep-tex: false
  agu-pdf:
    keep-tex: true    
